### ISSUE TITLE
Missing sources of pdfinfo and pdftotext

### ISSUE THREAD

**Issue by mandian-lx** [zotero/zotero-standalone-build#42]
I read in docs you use a customized version of pdfinfo and pdftotext. Please could you share the sources (or at least the patches) you use?

**Comment by dstillman** [comment]
We no longer use customized binaries on OS X and Linux.

For Windows, the main change isn't in the source — it's modifying a flag (can't remember which one) to prevent the console window from showing when the executable is run. We did also modify pdfinfo.exe to allow it to take an output text file as a parameter, but the diff for that was on our old SVN server, which isn't online anymore. I might be able to retrieve it, but it's also possible to use the stock pdfinfo using the bundled VB scripts, which I can explain if you're on Windows. (We ran into problems running VB scripts with security settings on some Windows computers, which is why that's not the default.)

**Comment by rmzelle** [comment]
> We did also modify pdfinfo.exe to allow it to take an output text file as a parameter, but the diff for that was on our old SVN server, which isn't online anymore.

@dstillman, looks like you already posted this before: https://gist.github.com/dstillman/7ff988a98076dc61e008/revisions (via https://github.com/zotero/zotero-standalone-build/issues/28#issuecomment-44618690)

**Comment by rmzelle** [comment]
And http://linux.die.net/man/1/pdftotext suggests that "-q" is the no-output flag:

> -q
    Don't print any messages or errors.

**Comment by mandian-lx** [comment]
Thank you for your answers.

@dstillman I am just interested in Linux version because I am packaging zotero for the distribution I use. After reading your answer I realized I missed the redirection script for pdfinfo. Just copying modules/zotero/resource/redirect.sh in the system binary path and renaming it solves my issue. So actually I am using the system binaries (I patched zotero in order to let it looks for them in /usr/bin, of course) and from my early tests all it works well.

@rmzelle your link refers to version 3.02 while I was searching for version 3.04.  pdftotext-Linux-x86_64 used by zotero has some different options with respect to the binary pdftotext installed on my system but dstillman said they don't modify it any more so I suppose it is only because my system is using a different version. In any way it seems now I don't need it any more. Maybe Debian packager could adopt a similar solution too.

**Comment by dstillman** [comment]
> @dstillman, looks like you already posted this before

Ah, thanks.

> And http://linux.die.net/man/1/pdftotext suggests that "-q" is the no-output flag

(That's just output from the command. It will still open a cmd.exe window when run unless a flag is changed on the binary.)
