### ISSUE TITLE
File Versions - There are none

### ISSUE THREAD

**Issue by brendanmeyer** [zotero/zotero-standalone-build#59]
Hi

I was hoping you would be able to implement file versions into the Windows builds.

There is currently incorrect information and no real file information in the installed files, see below.

Thank you
Brendan

![image](https://user-images.githubusercontent.com/16585315/31637899-9873fe0a-b31c-11e7-97b7-d5e8e6a6e4ec.png)

**Comment by dstillman** [comment]
We might be able to add this to the build script with https://github.com/electron/rcedit.

**Comment by brendanmeyer** [comment]
That would be very helpful with version detection in SCCM

**Comment by dstillman** [comment]
What matters here, the "File version" field or the "Product version" field?

**Comment by brendanmeyer** [comment]
File Version please, with the version to match the changelog version number
Thanks

**Comment by dstillman** [comment]
OK, I've added this for the current Zotero beta channel. The current release version of 5.0.96.3 is still 5.0.0.0, but the next release will have a proper version — either 5.0.96.4 if there's another Zotero 5 release or 6.0.0.0/6.0.1.0/6.0.2.0 for Zotero 6.0/6.0.1/6.0.2.

Since File Version seems to be limited to four integers, that won't show a proper version for beta builds — e.g., 5.0.97-beta.38 and all future 5.0.97 betas will be 5.0.97.0, as would the release build of 5.0.97. But people using SCCM probably aren't going to be managing beta builds. If someone really wants to, I assume there's a way to use Product Version, which will be a Mozilla [Manifest Version Format](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version/format) string (e.g., 5.0.97-beta.37+ddc7be75c).

**Comment by brendanmeyer** [comment]
Thank you very much

This should be very helpful, and I look forward to the next version release.
