### ISSUE TITLE
Blank context menus

### ISSUE THREAD

**Issue by UTH-Tuan** [zotero/zotero-standalone-build#79]
The menus (right click, context menus) have blank entries. 

I am using the latest MacOS on the desktop. I have attached a screenshot.
<img width="351" alt="Untitled" src="https://user-images.githubusercontent.com/7785012/71595977-5e95e700-2b03-11ea-9b1d-44f3c2c33de4.png">

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums at https://forums.zotero.org, where we're best able to help.

There've been a few reports of this but all we know is that it's fixed when people try in a new user account, so it's likely something about the configuration in the current user account. Using Dark Mode in Mojave (rather than Catalina) also caused it for one user:

https://forums.zotero.org/discussion/comment/344460/#Comment_344460
